apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command: 
            - /bin/sh
            - -c
            - "echo hello world; echo hello $(date) >> /opt/data/log"
            volumeMounts:
            - mountPath: "/opt/data"
              name: my-volume
          restartPolicy: OnFailure
          volumes:
          - name: my-volume
            persistentVolumeClaim:
                claimName: hello-pvc

